name:  Bug Report
description: Reporta un error o comportamiento inesperado en TYR
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por tomarte el tiempo de reportar un bug. Por favor completa la informaci贸n a continuaci贸n para ayudarnos a resolver el problema.

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n del Bug
      description: Una descripci贸n clara y concisa del bug
      placeholder: "Cuando hago X, esperaba Y pero ocurri贸 Z..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Pasos para Reproducir
      description: 驴C贸mo podemos reproducir este comportamiento?
      placeholder: |
        1. Ir a '...'
        2. Hacer click en '...'
        3. Escribir '...'
        4. Ver error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamiento Esperado
      description: 驴Qu茅 esperabas que sucediera?
      placeholder: Deber铆a mostrar...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Si aplica, a帽ade screenshots para explicar el problema
      placeholder: Arrastra y suelta im谩genes aqu铆

  - type: dropdown
    id: component
    attributes:
      label: Componente Afectado
      description: 驴Qu茅 parte de TYR est谩 afectada?
      options:
        - Backend (API FastAPI)
        - Frontend (Landing Page React)
        - App Streamlit
        - Modelo BERT
        - Dataset/Base de Conocimiento
        - Documentaci贸n
        - Otro
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Sistema Operativo
      placeholder: "ej. Windows 11, macOS 14.1, Ubuntu 22.04"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Versi贸n de Python
      placeholder: "ej. 3.10.5"
    validations:
      required: false

  - type: input
    id: node-version
    attributes:
      label: Versi贸n de Node.js (si aplica)
      placeholder: "ej. 18.16.0"
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Navegador (si aplica)
      placeholder: "ej. Chrome 120, Firefox 121, Safari 17"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Contexto Adicional
      description: Cualquier otra informaci贸n relevante sobre el problema
      placeholder: |
        - Logs de error
        - Configuraci贸n espec铆fica
        - Otros detalles

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: He buscado en los issues existentes y no encontr茅 uno similar
          required: true
        - label: Estoy usando la 煤ltima versi贸n de TYR
          required: false
        - label: He le铆do la documentaci贸n relevante
          required: false
